# Meta Data for SEO

## Homepage
title = "Eduki"
titleSeparator = "-"
titleAddition = "Simplifying K-12 math education"
description = "Eduki is an ed-tech startup with goal to transform K-12 math education."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["eduki-screenshot.png"]
ogLocale = "en_US"
domainTLD = "myeduki.com"
titleHome = "Eduki"

## Twitter Cards
twitterSite = "@myeduki"
twitterCreator = "@myeduki"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Eduki"
schemaAuthor = "Rajeev Amatya"
schemaAuthorTwitter = "https://twitter.com/rajeevamatya"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/rajeevamatya/"
schemaAuthorGitHub = "https://github.com/rajeevamatya"
schemaLocale = "en-US"
schemaLogo = "eduki-logo-square-red.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "eduki-screenshot"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/myeduki"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/rajeevmatya/eduki-hugo-site"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Made available for free by <a class=\"text-muted\" href=\"https://www.myeduki.com/\">Eduki</a>"
# Feed
copyRight = "Copyright (c) 2021-2023 Eduki Learning P. Lte."

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the new Eduki with free math lessons.<a class=\"alert-link stretched-link\" href=\"https://myeduki.com/lessons/\" target=\"_blank\" rel=\"noopener\">Check out the free lessons</a>"
alertText = "Introducing the new Eduki with free math lessons.<a class=\"alert-link stretched-link\" href=\"https://myeduki.com/lessons/\">Check out the free lessons</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/rajeevamatya/eduki-hugo-site"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
